-- Actualiza año, km, precio y condicion en metadata, y reescribe content, de autos_disponibles.
-- Generado por scripts/gen-stock-update-sql.mjs desde stock.csv (2026-07-23). No editar a mano.
--
-- Idempotente: se puede correr las veces que haga falta.
-- Pisa SÓLO las 4 claves que cambian (año, km, precio, condicion) y reescribe content.
-- NO toca color, descripcion, condicionantes, tamano, fotos, foto_principal, marca, modelo, id
-- ni embedding. marca y modelo quedan intactos (siguen atados a las fotos).
--
-- BACKUP ANTES DE CORRER:
--   CREATE TABLE autos_disponibles_backup_20260723 AS SELECT * FROM autos_disponibles;

UPDATE autos_disponibles a
SET metadata = a.metadata || jsonb_build_object(
      'año',      v.anio,
      'km',       v.km,
      'precio',   v.precio,
      'condicion', v.condicion
    ),
    content = v.content
FROM (VALUES
  (1, 2023, '28000', 16800000, 'Usado', 'Fiat Cronos 2023, color gris, 28000 km. Sedán, 4 puertas, 5 asientos. Motor 1.3L de 99 HP, nafta, transmisión manual. Consumo promedio aproximado: 6.5. Condición: usado. Precio: $16800000 ARS. Equipamiento: aire acondicionado, pantalla multimedia. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-1-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-1-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-1-3.webp'),
  (2, 2018, '110000', 9200000, 'Usado', 'Volkswagen Gol Trend 2018, color blanco, 110000 km. Hatchback, 5 puertas, 5 asientos. Motor 1.6L de 101 HP, nafta, transmisión manual. Consumo promedio aproximado: 7.0. Condición: usado. Precio: $9200000 ARS. Equipamiento: aire acondicionado. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-2-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-2-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-2-3.webp'),
  (3, 2017, '105000', 8200000, 'Usado', 'Ford Fiesta 2017, color azul, 105000 km. Hatchback, 5 puertas, 5 asientos. Motor 1.6L de 120 HP, nafta, transmisión manual. Consumo promedio aproximado: 6.8. Condición: usado. Precio: $8200000 ARS. Equipamiento: aire acondicionado, pantalla multimedia. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-3-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-3-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-3-3.webp'),
  (4, 2019, '45000', 12500000, 'Usado', 'Toyota Etios 2019, color gris, 45000 km. Hatchback, 5 puertas, 5 asientos. Motor 1.5L de 103 HP, nafta, transmisión manual. Consumo promedio aproximado: 6.3. Condición: usado. Precio: $12500000 ARS. Equipamiento: aire acondicionado. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-4-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-4-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-4-3.webp'),
  (5, 2022, '35000', 24800000, 'Usado', 'Toyota Corolla XEI CVT 2022, color gris, 35000 km. Sedán, 4 puertas, 5 asientos. Motor 1.8L de 140 HP, nafta, transmisión cvt. Consumo promedio aproximado: 7.2. Condición: usado. Precio: $24800000 ARS. Equipamiento: aire acondicionado, pantalla multimedia, cámara de retroceso, sensores de estacionamiento. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-5-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-5-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-5-3.webp'),
  (6, 2023, '24000', 31000000, 'Seminuevo', 'Volkswagen Vento 2023, color blanco, 24000 km. Sedán, 4 puertas, 5 asientos. Motor 1.4L Turbo de 150 HP, nafta, transmisión automática. Consumo promedio aproximado: 7.5. Condición: seminuevo. Precio: $31000000 ARS. Equipamiento: aire acondicionado, pantalla multimedia, cámara de retroceso, sensores de estacionamiento. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-6-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-6-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-6-3.webp'),
  (7, 2024, '12000', 21500000, 'Seminuevo', 'Chevrolet Onix 2024, color rojo, 12000 km. Sedán, 4 puertas, 5 asientos. Motor 1.2L Turbo de 116 HP, nafta, transmisión manual. Consumo promedio aproximado: 6.0. Condición: seminuevo. Precio: $21500000 ARS. Equipamiento: aire acondicionado, pantalla multimedia, cámara de retroceso. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-7-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-7-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-7-3.webp'),
  (8, 2025, '8000', 21000000, 'Seminuevo', 'Peugeot 208 2025, color azul, 8000 km. Hatchback, 5 puertas, 5 asientos. Motor 1.6L de 115 HP, nafta, transmisión manual. Consumo promedio aproximado: 6.6. Condición: seminuevo. Precio: $21000000 ARS. Equipamiento: aire acondicionado, pantalla multimedia. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-8-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-8-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-8-3.webp'),
  (9, 2020, '55000', 19800000, 'Usado', 'Ford EcoSport 2020, color negro, 55000 km. SUV, 5 puertas, 5 asientos. Motor 1.5L de 123 HP, nafta, transmisión manual. Consumo promedio aproximado: 8.0. Condición: usado. Precio: $19800000 ARS. Equipamiento: aire acondicionado, pantalla multimedia, cámara de retroceso, sensores de estacionamiento. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-9-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-9-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-9-3.webp'),
  (10, 2025, '5200', 34000000, 'Seminuevo', 'Volkswagen T-Cross 2025, color blanco, 5200 km. SUV, 5 puertas, 5 asientos. Motor 1.6L de 110 HP, nafta, transmisión automática. Consumo promedio aproximado: 7.3. Condición: seminuevo. Precio: $34000000 ARS. Equipamiento: aire acondicionado, pantalla multimedia, cámara de retroceso, sensores de estacionamiento. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-10-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-10-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-10-3.webp'),
  (11, 2023, '31000', 22500000, 'Usado', 'Renault Duster 2023, color gris, 31000 km. SUV, 5 puertas, 5 asientos. Motor 1.6L de 106 HP, nafta, transmisión manual. Consumo promedio aproximado: 8.5. Condición: usado. Precio: $22500000 ARS. Equipamiento: aire acondicionado, pantalla multimedia, cámara de retroceso. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-11-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-11-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-11-3.webp'),
  (12, 2021, '42000', 25500000, 'Usado', 'Jeep Renegade 2021, color verde, 42000 km. SUV, 5 puertas, 5 asientos. Motor 1.8L de 139 HP, nafta, transmisión automática. Consumo promedio aproximado: 8.8. Condición: usado. Precio: $25500000 ARS. Equipamiento: aire acondicionado, pantalla multimedia, cámara de retroceso, sensores de estacionamiento. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-12-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-12-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-12-3.webp'),
  (13, 2021, '95000', 38000000, 'Usado', 'Toyota Hilux 4x4 2021, color blanco, 95000 km. Pickup, 4 puertas, 5 asientos. Motor 2.8L de 177 HP, diesel, transmisión manual. Consumo promedio aproximado: 9.5. Condición: usado. Precio: $38000000 ARS. Equipamiento: aire acondicionado, pantalla multimedia, cámara de retroceso, sensores de estacionamiento. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-13-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-13-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-13-3.webp'),
  (14, 2024, '18000', 57000000, 'Seminuevo', 'Ford Ranger 4x4 2024, color gris, 18000 km. Pickup, 4 puertas, 5 asientos. Motor 3.2L de 200 HP, diesel, transmisión automática. Consumo promedio aproximado: 10.2. Condición: seminuevo. Precio: $57000000 ARS. Equipamiento: aire acondicionado, pantalla multimedia, cámara de retroceso, sensores de estacionamiento. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-14-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-14-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-14-3.webp'),
  (15, 2018, '135000', 32000000, 'Usado', 'Volkswagen Amarok 4x4 2018, color negro, 135000 km. Pickup, 4 puertas, 5 asientos. Motor 2.0L de 180 HP, diesel, transmisión manual. Consumo promedio aproximado: 9.8. Condición: usado. Precio: $32000000 ARS. Equipamiento: aire acondicionado, pantalla multimedia, cámara de retroceso, sensores de estacionamiento. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-15-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-15-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-15-3.webp'),
  (16, 2022, '68000', 39500000, 'Usado', 'Chevrolet S10 4x2 2022, color blanco, 68000 km. Pickup, 4 puertas, 5 asientos. Motor 2.8L de 200 HP, diesel, transmisión manual. Consumo promedio aproximado: 9.6. Condición: usado. Precio: $39500000 ARS. Equipamiento: aire acondicionado, pantalla multimedia, cámara de retroceso, sensores de estacionamiento. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-16-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-16-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-16-3.webp'),
  (17, 2021, '82000', 18500000, 'Usado', 'Renault Kangoo 2021, color blanco, 82000 km. Utilitario, 5 puertas, 2 asientos. Motor 1.6L de 105 HP, nafta, transmisión manual. Consumo promedio aproximado: 7.8. Condición: usado. Precio: $18500000 ARS. Equipamiento: aire acondicionado. URLs de fotos de este auto (usar EXACTAMENTE estas, no inventar): https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-17-1.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-17-2.webp | https://qfmsdgjtlduravrtqrif.supabase.co/storage/v1/object/public/fotos-vehiculos-stock/foto-17-3.webp')
) AS v(id, anio, km, precio, condicion, content)
WHERE (a.metadata->>'id')::int = v.id;

-- Verificación: 17 filas, metadata y content coherentes.
SELECT (metadata->>'id')::int AS id,
       metadata->>'marca' || ' ' || (metadata->>'modelo') AS auto,
       (metadata->>'año')::int AS anio,
       metadata->>'km' AS km,
       '$' || replace(to_char((metadata->>'precio')::bigint, 'FM999G999G999'), ',', '.') AS precio,
       left(content, 60) AS content_ini
FROM autos_disponibles
ORDER BY 1;
